### PR TITLE
Add favicon for people using web browser

### PR DESCRIPTION
**Pull request by jared-hughes**

### CODE REVIEW

**Review by adityarathod — COMMENTED** [review]
Nice job. But for `app/index.html`, you are linking to a non-existent resource. Try opening your fork by running `python -m SimpleHTTPServer` in the project root. The favicon doesn't appear on the `app/index.html` page.

**Comment by jared-hughes** [comment]
Browser caching was making it seem like it was working. It's fixed now.

**Comment by applecrazy** [comment]
Merging into `master`. Hopefully nothing breaks.

**Comment by applecrazy** [comment]
Yep. We're good. Nothing broke.

image

**Pull request merged**
